### ISSUE TITLE
Prereleases not updating correctly

### ISSUE THREAD

**Issue by virus2016** [qiwi/multi-semantic-release#75] opened 2022-06-12 03:05 UTC
## Issue type
* [x] bug report
* [ ] idea
* [ ] question
* [ ] other

## Expected behavior
When using prerelease, packages that are a dependency on one and other are updated using 1 commit, the prelease version for a should match the version of the new updated dependency.

## Actual behavior
The parent dependency is updated as expected however when the next package is triggered and depends on the parent, MSR does to update the dependency but it adds an extra patch? 

Example:

Parent package updated to 1.0.0-beta.1
Child package is told to update Parent to 1.0.0-beta.2 (it should be 1.0.0-beta.1)

* [x] I've read the docs. This case is not mentioned
* [x] Similar issue does not exist

## Steps to reproduce

Create 2 packages
Have one dependent on the other
Create a prerelease release.rc for both
Run MSR

My example below:

<img width="784" alt="image" src="https://user-images.githubusercontent.com/11227384/173212448-b74fbfe6-2ad0-4029-bc92-206eed33797c.png">

<img width="619" alt="image" src="https://user-images.githubusercontent.com/11227384/173212437-bc9cf806-a859-467c-ae65-148a7b7827ca.png">

## Specifications

- version: 6.4.0
- platform: Linux (Docker)
- ci: Gitlab runner

**Comment by virus2016** [comment] 2022-06-12 03:14
Just to add, works on the first release but if you try again... it will fail.

**Comment by antongolub** [comment] 2022-06-12 14:34
@virus2016, 

could you plz add a testing fixture for your case?

**Comment by virus2016** [comment] 2022-06-12 23:46
Will do!

**Comment by virus2016** [comment] 2022-06-13 00:35
We can just use the one that is already there. Just writing some tests around this.

**Comment by virus2016** [comment] 2022-06-13 00:57
@antongolub I have added a test case for this issue. I am not sure why it does not update the dependency but it is not what I am experiencing. I might of missed something.

**Comment by oljekechoro** [comment] 2022-07-05 07:30
@virus2016, hi! I started working on this issue

**Comment by virus2016** [comment] 2022-07-06 21:42
Do you need me to provide anything else?

**Comment by oljekechoro** [comment] 2022-07-08 11:15
@virus2016, It will take more time, because I am new in this package as a maintainer. Could you reproduce your issue in your test case? There was a problem with module caching, I wrote in your PR.

**Comment by virus2016** [comment] 2022-07-09 09:42
@oljekechoro ive tried to recreate the issue above. Here is a sequence to try and help you. 

- Update files in 2 different packages using the commit message "fix: updated types"
- Push to ci
- Runs Multi semantic release
- first package is bumped 1.0.1
- Second package has a dependency on first package. First package is currently 1.0.0 in the package.json of the second package
- Second package updates dependencies in package however in the package.json the first package [1.0.1] is bumped to 1.0.2
- Release fails

It looks like when the second package reads the first package version it takes 1.0.1 and bumps that rather it should just match the version of the first package was bumped. Does that make sense? 

There might be a bigger issue here where that we might need to have an order for which packages go out first? I don't know if MSR already does this. Here are my 2 options below:

Scan and bump all the packages that that have the least dependencies to other local packages first. Example, 3 packages and 2 of them have a dependency on the 3rd, make sure the release order is 3 > 1 > 2.

Another option could be that you could add config that allows us to tell multi semantic release the order in which packages we want the releases to go out in. 

I think the last option is the best where you allow config driven rather than a glob and using yarn workspaces.

**Comment by virus2016** [comment] 2022-08-07 23:47
Bump ;-)

**Comment by oljekechoro** [comment] 2022-08-10 08:15
@virus2016, sorry, I had to switch to our internal tasks, I will continue as soon as I can

**Comment by virus2016** [comment] 2022-08-28 20:28
No worries ;-) - I had a look but i think this is a complex one @oljekechoro

**Comment by aarne** [comment] 2023-07-09 10:43
Considering the state of the project is it correct to assume that this one will not get any attention?

**Comment by antongolub** [comment] 2023-07-09 16:46
@aarne,

I'm afraid, I have nothing to reassure you. Our in-house development is forced to abandon the GitHub in favor of a different solution that does not support git notes, which [is required for semrel](https://github.com/semantic-release/semantic-release/blob/4a1378d6c7f10f2d429bb64084bbff3bc5761df7/lib/git.js#L146) and its extras like multi-semantic-release. Therefore, we are focusing our efforts on the alternative release tools development — [zx-bulk-release](https://github.com/semrel-extra/zx-bulk-release/), [zx-semrel](https://github.com/semrel-extra/zx-semrel/zx-semrel). What remains unchanged is that we are ready, as before, to share the results with everyone. 

PS I would be happy to find another maintainer for [the upstream project](https://github.com/dhoulb/multi-semantic-release).

**Comment by hanseltime** [comment] 2023-09-16 23:31
I have a fix for this behavior that I've pushed up as a PR.  I would love to get this pushed and released as part of the actual package so please feel free to have any maintainer reach out to me or let me know if it would be better for me to publish out a fork, etc.

Thanks!

**Comment by prisis** [comment] 2023-09-28 22:27
> @aarne,
> 
> I'm afraid, I have nothing to reassure you. Our in-house development is forced to abandon the GitHub in favor of a different solution that does not support git notes, which [is required for semrel](https://github.com/semantic-release/semantic-release/blob/4a1378d6c7f10f2d429bb64084bbff3bc5761df7/lib/git.js#L146) and its extras like multi-semantic-release. Therefore, we are focusing our efforts on the alternative release tools development — [zx-bulk-release](https://github.com/semrel-extra/zx-bulk-release/), [zx-semrel](https://github.com/semrel-extra/zx-semrel/zx-semrel). What remains unchanged is that we are ready, as before, to share the results with everyone.
> 
> PS I would be happy to find another maintainer for [the upstream project](https://github.com/dhoulb/multi-semantic-release).

Created a fork with all needed patched and found bug tickets fixed in this repo https://github.com/anolilab/multi-semantic-release -> i could provided all changes back, but i changed a lot of the structure and removed dead code in the repo and is support all versions of the semantic-release

**Closed** 2023-10-16 07:24 UTC
