### ISSUE TITLE
Question: merging back into source?

### ISSUE THREAD

**Issue by StevenLangbroek** [qiwi/multi-semantic-release#8] opened 2020-06-15 08:01 UTC
Hey folks! I have a question; did you ever discuss merging this back into source with the original authors? We're evaluating a bunch of tools, and I'd like to understand what the plans re: long-term maintenance are. Thanks!

**Comment by antongolub** [comment] 2020-06-15 08:20
Hi @StevenLangbroek

There is no reason to worry about that. 
We're constantly updating the original repository with PRs:
https://github.com/dhoulb/multi-semantic-release/pull/16 (BF, not merged yet)
https://github.com/dhoulb/multi-semantic-release/pull/15
https://github.com/dhoulb/multi-semantic-release/pull/9
https://github.com/dhoulb/multi-semantic-release/pull/2

This repository is just our experimental site for improvements and сanary builds.

**Comment by StevenLangbroek** [comment] 2020-06-15 08:21
Super happy to hear that! Thanks so much 🙏

**Comment by antongolub** [comment] 2020-06-15 08:37
We use monorepos in production, so we have to fix **msr** issues and publish new versions asap.  @qiwi npm scope is needed to just speed up the process.

**Comment by StevenLangbroek** [comment] 2020-06-15 08:47
@antongolub hehe, have you considered using `prerelease: true` for that ;)

**Comment by antongolub** [comment] 2020-06-15 10:15
@StevenLangbroek
`prerelease` / `beta` is a good practice. Moreover, this is exactly how we release our fork.
[npm/@qiwi/multi-semantic-release](https://www.npmjs.com/package/@qiwi/multi-semantic-release) (`Versions` tab)
Unfortunately at this moment, I have not enough permissions in the original repo. If @dhoulb deems it possible, then I could maintain his repository too. If not, anyway @qiwi will continue to develop **msr** in the current format.

**Comment by dhoulb** [comment] 2020-06-16 16:20
@antongolub Consider it done :)

**Comment by antongolub** [comment] 2020-06-19 07:57
@dhoulb Thanks, Dave.
@StevenLangbroek I guess, the issue is now completely resolved.

**Closed by antongolub** 2020-06-19 07:57 UTC
Labels: question

**Comment by StevenLangbroek** [comment] 2020-06-19 08:09
Thanks so much all 🙏
